---
train:

    params:
        batch_size: 128
        epoch: 100
        lr: 0.0001
        decay: 0.5
        decay_step: 1000
        warmup: 0
    
    save:
        metapath: "result"
        folder: gaze360
        model_name: dg
        step: 10

    data:
        image: "/root/autodl-tmp/Gaze360-New/Image/"
        label: "/root/autodl-tmp/Gaze360-New/Label/gaze360_id_wnorm.label"
        header: True
        name: gaze360
        isFolder: False
    
    device: 0

    reader: reader
# dropout = 0
# dim_feed = 512

